# Commented sections to suits Apex
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: servicemeshoperator
#   namespace: openshift-operators
# spec:
#   channel: stable
#   name: servicemeshoperator
#   installPlanApproval: Automatic
#   source: redhat-operators
#   sourceNamespace: openshift-marketplace
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: kiali-ossm
#   namespace: openshift-operators
# spec:
#   channel: stable
#   name: kiali-ossm
#   installPlanApproval: Automatic
#   source: redhat-operators
#   sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace