kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kserve-prometheus-k8s
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - services
      - endpoints
      - pods
