apiVersion: v1
kind: Secret
metadata:
  annotations:
    serving.kserve.io/s3-endpoint: s3.amazonaws.com # s3.amazonaws.com # replace with your s3 endpoint e.g minio-service.kubeflow:9000
    serving.kserve.io/s3-usehttps: "1" # by default 1, if testing with minio you can set to 0
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-useanoncredential: "true" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
    #serving.kserve.io/s3-verifyssl: "0"
  name: storage-config
stringData:
  "AWS_ACCESS_KEY_ID": "*************"
  "AWS_SECRET_ACCESS_KEY": "************************"
